# The format version is an indicator of the compatibility of community exercises with the
# Rustlings program.
# The format version is not the same as the version of the Rustlings program.
# In case Rustlings makes an unavoidable breaking change to the expected format of community
# exercises, you would need to raise this version and adapt to the new format.
# Otherwise, the newest version of the Rustlings program won't be able to run these exercises.
format_version = 1

# Optional multi-line message to be shown to users when just starting with the exercises.
welcome_message = """Welcome to the Leetcode75 Rustlings exercises."""

# Optional multi-line message to be shown to users after finishing all exercises.
final_message = """We hope that you found the exercises helpful :D"""

# Repeat this section for every exercise.
# [[exercises]]
# # Exercise name which is the exercise file name without the `.rs` extension.
# name = "array_string1"
# hint = """
# String and Array
# """
# test = true

# Optional directory name to be provided if you want to organize exercises in directories.
# If `dir` is specified, the exercise path is `exercises/DIR/NAME.rs`
# Otherwise, the path is `exercises/NAME.rs`
# dir = "???"

# Rustlings expects the exercise to contain tests and run them.
# You can optionally disable testing by setting `test` to `false` (the default is `true`).
# In that case, the exercise will be considered done when it just successfully compiles.
# test = true

# Rustlings will always run Clippy on exercises.
# You can optionally set `strict_clippy` to `true` (the default is `false`) to only consider
# the exercise as done when there are no warnings left.
# strict_clippy = false

# A multi-line hint to be shown to users on request.
#hint = """???"""


# [[exercises]]
# name = ""
# hint = """
# """
# test = true


# String and Array #

# 1768. Merge Strings Alternately
[[exercises]]
name = "merge_alternatively"
dir = "array_string"
hint = """
Use two pointers, one pointer for each string.
Alternately choose the character from each pointer,and move the pointer upwards.
"""
test = true

# 1071. Greatest Common Divisor of Strings
[[exercises]]
name = "gcd_of_strings"
dir = "array_string"
hint = """
The greatest common divisor must be a prefix of each string, so we can try all prefixes.
"""
test = true

# 1431. Kids With the Greatest Number of Candies
[[exercises]]
name = "kids_with_candies"
dir = "array_string"
hint = """
For each kid check if candies[i] + extraCandies â‰¥ maximum in Candies[i].
"""
test = true

# 605. Can Place Flowers
[[exercises]]
name = "can_place_flowers"
dir = "array_string"
hint = """
Make sure to place flowers when they can be placed.
"""
test = true

# 345. Reverse Vowels of a String
[[exercises]]
name = "reverse_vowels"
dir = "array_string"
hint = """
Use a stack to store the vowels.
"""
test = true

# 151. Reverse Words in a String
[[exercises]]
name = "reverse_words"
dir = "array_string"
hint = """
Split the string into words, and reverse each word.
"""
test = true

# 238. Product of Array Except Self
[[exercises]]
name = "product_except_self"
dir = "array_string"
hint = """
Think how you can efficiently utilize prefix and suffix products to calculate the product of all elements except self for each index.
"""
test = true

# 334. Increasing Triplet Subsequence
[[exercises]]
name = "increasing_triplet"
dir = "array_string"
hint = """
Your on your own.
"""
test = true

# 443. String Compression
[[exercises]]
name = "compress"
dir = "array_string"
hint = """
How do you know if you are at the end of a consecutive group of characters?
"""
test = true

# Two Pointers #

# 283. Move Zeroes
[[exercises]]
name = "move_zeros"
dir = "two_pointers"
hint = """
The idea would be to have one pointer for iterating the array and another pointer that just works on the non-zero elements of the array.
"""
test = true

# 392. Is Subsequence
[[exercises]]
name = "is_subsequence"
dir = "two_pointers"
hint = """
Iterate through both string simultaneously.
"""
test = true

# 11. Container With Most Water
[[exercises]]
name = "max_area"
dir = "two_pointers"
hint = """
Set one pointer to the left and one to the right of the array. Always move the pointer that points to the lower line.
"""
test = true

# 1679. Max Number of K-Sum Pairs
[[exercises]]
name = "max_operations"
dir = "two_pointers"
hint = """
For each possible value x, it can be paired up with k - x.
"""
test = true

# Sliding Window #

# 643. Maximum Average Subarray I
[[exercises]]
name = "find_max_average"
dir = "sliding_window"
hint = """
Track the changes to the max sum.
"""
test = true

# 1456. Maximum Number of Vowels in a Substring of Given Length
[[exercises]]
name = "max_vowels"
dir = "sliding_window"
hint = """
Keep a window of size k and maintain the number of vowels in it.
"""
test = true

# 1004. Max Consecutive Ones III
[[exercises]]
name = "longest_ones"
dir = "sliding_window"
hint = """
The way to shrink or expand a window would be based on the number of zeros that can still be flipped and so on.
"""
test = true

# 1493. Longest Subarray of 1's After Deleting One Element
[[exercises]]
name = "longest_subarray"
dir = "sliding_window"
hint = """
Maintain a sliding window where there is at most one zero in it.
"""
test = true

# Prefix Sum #

# 1732. Find the Highest Altitude
[[exercises]]
name = "largest_altitude"
dir = "prefix_sum"
hint = """
Getting the altitudes can be done by getting the prefix sum array of the given array.
"""
test = true

# 724. Find Pivot Index
[[exercises]]
name = "pivot_index"
dir = "prefix_sum"
hint = """
For each index i, check if sumLeft[i] equals sumRight[i]. If so, return i. If no such i is found, return -1.
"""
test = true

# Hash Map / Set #

# 2215. Find the Difference of Two Arrays
[[exercises]]
name = "find_difference"
dir = "hashmap_set"
hint = """
For each integer in nums1, check if it exists in nums2.
"""
test = true

# 1207. Unique Number of Occurrences
[[exercises]]
name = "unique_occurrences"
dir = "hashmap_set"
hint = """
Find the number of occurrences of each element in the array using a hash map.
"""
test = true

# 1657. Determine if Two Strings Are Close
[[exercises]]
name = "close_strings"
dir = "hashmap_set"
hint = """
Operation 1 allows you to freely reorder the string.
Operation 2 allows you to freely reassign the letters' frequencies.
"""
test = true

# 2352. Equal Row and Column Pairs
[[exercises]]
name = "equal_pairs"
dir = "hashmap_set"
hint = """
Hint 1: We can use nested loops to compare every row against every column.
Hint 2: Another loop is necessary to compare the row and column element by element.
Hint 3: It is also possible to hash the arrays and compare the hashed values instead.
"""
test = true

# Stack #

# 2390. Removing Stars From a String
[[exercises]]
name = "remove_stars"
dir = "stack"
hint = """
Use a stack to store the characters. Pop one character off the stack at each star. Otherwise, we push the character onto the stack.
"""
test = true

# 735. Asteroid Collision
[[exercises]]
name = "asteroid_collision"
dir = "stack"
hint = """
Say a row of asteroids is stable. What happens when a new asteroid is added on the right?
"""
test = true

# 394. Decode String
[[exercises]]
name = "decode_string"
dir = "stack"
hint = """
Good Luck!
"""
test = true

# Queue #

# 933. Number of Recent Calls
[[exercises]]
name = "recent_counter"
dir = "queue"
hint = """
Use queue to track the calls
"""
test = true

# 649. Dota2 Senate
[[exercises]]
name = "predict_party_victory"
dir = "queue"
hint = """
Use two queues and assign tickets to the senators
"""
test = true

# Linked List #

# 2095. Delete the Middle Node of a Linked List
[[exercises]]
name = "delete_middle"
dir = "linked_list"
hint = """
If a point with a speed s moves n units in a given time, a point with speed 2 * s will move 2 * n units at the same time. Can you use this to find the middle node of a linked list?
"""
test = true

# 328. Odd Even Linked List
[[exercises]]
name = "odd_even_list"
dir = "linked_list"
hint = """
Keep track of each next pointer.
"""
test = true

# 206. Reverse Linked List
[[exercises]]
name = "reverse_list"
dir = "linked_list"
hint = """
Iterate through the list and swap the next pointers.
"""
test = true

# 2130. Maximum Twin Sum of a Linked List
[[exercises]]
name = "pair_sum"
dir = "linked_list"
hint = """
Use two different pointers pointing to the first nodes of the two halves of the linked list. The second pointer will point to the first node of the reversed half, which is the (n-1-i)th node in the original linked list. By moving both pointers forward at the same time, we find all twin sums.
"""
test = true

